### PR TITLE
[nrf toup] boot: zephyr: Update USB CDC ACM device name

### PR DESCRIPTION
**Pull request by Qbicz**
Follow the device name changes in Zephyr.

Signed-off-by: Filip Kubicz <filip.kubicz@nordicsemi.no>

### CODE REVIEW

**Comment by Qbicz** [comment]
Needed for upmerge https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/765

@nvlsianpu @rlubos Can you review?

**Comment by Qbicz** [comment]
@rlubos please verify that it should have [toup] (We want it to be pushed to upstream mcuboot too). Should I open another PR to upstream mcuboot?

**Comment by rlubos** [comment]
@Qbicz Yes, if it's intended to upstream, then we need [nrf toup], or [nrf fromlist] if the upstream PR already exists.
@nvlsianpu Can you clarify on how to proceed with the upstream PR?

**Comment by nvlsianpu** [comment]
Pleas Open upsteram PR with the same content as well.

**Comment by nvlsianpu** [comment]
@ChristopherBittner Don't know what cause ci failure on arepo checkout stage.

@rlubos You may merge this despite of CI failure,.

**Comment by rlubos** [comment]
@nvlsianpu Thanks, let's wait for the -nrf CI to finish.

**Comment by Qbicz** [comment]
Opened https://github.com/JuulLabs-OSS/mcuboot/pull/481 to upstream.

**Pull request merged**
