### PR TITLE
[nrf mergeup] Upmerge 29 01 2020

### PR DESCRIPTION
**Pull request by rlubos**

### CODE REVIEW

**Comment by hakonfam** [comment]
I created a patch here https://github.com/rlubos/fw-nrfconnect-mcuboot/pull/1 let me know if you want me to PR against this repo instead. Not sure what i easiest for you.

**Comment by rlubos** [comment]
Thank you @hakonfam, I'll merge them as soon as @nvlsianpu reviews them.

**Comment by rlubos** [comment]
@hakonfam Your PRs are merged now.

**Comment by rlubos** [comment]
@hakonfam @nvlsianpu Is the CI supposed to pass on an upmerge PR? The failures reported are inherited from upstream...

**Comment by hakonfam** [comment]
https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/pull/76

https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/latest%2Ffw-nrfconnect-mcuboot/detail/PR-76/7/pipeline

To me it looks like this was done to make it green 
https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/pull/76#issuecomment-576570969

**Comment by nvlsianpu** [comment]
Any idea why commit `[nrf fromlist] boot: zephyr: Fix Kconfig inclusion`:(https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/pull/81/commits/e67f4f85340fdc0a2a4382a4021e6ee1e614be81)  is not required for pass zephyr-rtos CI upsteram? @thst-nordic @mbolivar

**Comment by mbolivar** [comment]
> Any idea why commit `[nrf fromlist] boot: zephyr: Fix Kconfig inclusion`:([e67f4f8](https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/commit/e67f4f85340fdc0a2a4382a4021e6ee1e614be81)) is not required for pass zephyr-rtos CI upsteram? @thst-nordic @mbolivar

No idea, but I usually get a bunch of warnings upgraded to errors when I do a mergeup that are just left as  warnings upstream, so I wouldn't be surprised if it's something like that.

**Pull request merged**
