### PR TITLE
[nrf fromtree] boot: zephyr: boards: add Actinius Icarus board

### PR DESCRIPTION
**Pull request by sigvartmh**
Add Actinius Icarus board configuration to be able to enter serial
recovery mode

Signed-off-by: Iosif Macesanu <iosif@actinius.com>

### CODE REVIEW

**Comment by sigvartmh** [comment]
Add this directly to the backport branch to get it inn before release.

**Comment by nvlsianpu** [comment]
Like I see it won't go into release - better integrate this via upmereg then,

**Comment by sigvartmh** [comment]
yup

**Comment by mbolivar** [comment]
Closing this one then

**Pull request closed without merging**
