### PR TITLE
[nrf fromlist] boot: serial recovery: Add pca10090 default detect pin

### PR DESCRIPTION
**Pull request by andvib**
Add button 1 as default serial detect pin for nrf9160_pca10090

Signed-off-by: Andreas Vibeto <andreas.vibeto@nordicsemi.no>

### CODE REVIEW

**Comment by andvib** [comment]
cc @nvlsianpu

**Comment by nvlsianpu** [comment]
@SebastianBoe do we want to avoid any upmerges during release freeze?

**Comment by nvlsianpu** [comment]
@andvib Pleas send this patch to upsteram as well.

**Comment by SebastianBoe** [comment]
> @SebastianBoe do we want to avoid any upmerges during release freeze?

We want to block new features, and merge fixes and doc changes.

**Pull request merged**
