### PR TITLE
[nrf noup] Disable flash protection for nrf9160_pca20035

### PR DESCRIPTION
**Pull request by sigvartmh**
To keep backward compatibility with previous versions of the thingy:91
firmware we need to disable flash protection of mcuboot as it has
unaligned sizes for the upgrade slots and itself.

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

### CODE REVIEW

**Comment by hakonfam** [comment]
@sigvartmh  please check the gitlint issue

**Comment by sigvartmh** [comment]
@hakonfam Fixed.

**Comment by hakonfam** [comment]
@jtguggedal @bjda @joakimtoe I want an ACK from one of you guys before merging.

**Comment by sigvartmh** [comment]
@jorgenmk Can you confirm that this fixes the bug with MCUBoot on thingy?

**Comment by jorgenmk** [comment]
@sigvartmh Fix is working

**Pull request merged**
