### PR TITLE
[DNM] [nrf mergeup] Mergeup ac55554

### PR DESCRIPTION
**Pull request by nvlsianpu**
This is upmerge to v1.4.0

- TLV parsing reworked
- new protected TLV format
- kconfig option for multi image
- imgtool: allow address adjustment in output hex 
- existing features code rework (code optimization and sharing)

- bugfixes: pre-release version stabilization

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@carlescufi, @thst-nordic 
Zephyr build mcuboot doesn't use ext/mbedtls submodule. For Zephyr/NCS there is neither need for use this submodule nor for pull it via west to ext/mbedtls path.
Zephyr build uses mbedtls bundled into zephyr (except mbedtls-asn1 which is copy-paste into mcuboot ext/ sources)

**Comment by carlescufi** [comment]
> @carlescufi, @thst-nordic
> Zephyr build mcuboot doesn't use ext/mbedtls submodule. For Zephyr/NCS there is neither need for use this submodule nor for pull it via west to ext/mbedtls path.
> Zephyr build uses mbedtls bundled into zephyr (except mbedtls-asn1 which is copy-paste into mcuboot ext/ sources)

Thanks @nvlsianpu . CC @mbolivar. How do we fix CI though?

**Comment by nvlsianpu** [comment]
^^ simplest way would be disabling `pylint` module in check-compliance run (`-e pylint`). Better would be instructing the pylint run to skip problematic location.

**Comment by carlescufi** [comment]
> ^^ simplest way would be disabling `pylint` module in check-compliance run (`-e pylint`). Better would be instructing the pylint run to skip problematic location.

That would probably cause upmerges to fail if there are changes to that submodule. I wonder if we could just disable pylint instead? Could you try this @thst-nordic and @nvlsianpu ?

**Comment by nvlsianpu** [comment]
^^ yes will try.

**Comment by nvlsianpu** [comment]
@ru-fu, @carlescufi  CI failed now on DOC as the documentation wrapper is not update on `nrf` master. Such patch is in manifest counterpart: https://github.com/NordicPlayground/fw-nrfconnect-nrf. Can I apply separate patch with wrapper update to `nrf` and merge it for making thi CI green?

**Comment by carlescufi** [comment]
> @ru-fu, @carlescufi CI failed now on DOC as the documentation wrapper is not update on `nrf` master. Such patch is in manifest counterpart: https://github.com/NordicPlayground/fw-nrfconnect-nrf. Can I apply separate patch with wrapper update to `nrf` and merge it for making thi CI green?

Yes, I don't see why not. Please make sure to copy @thst-nordic and @ulfalizer and myself in the PR you send against fw-nrfconnect-nrf

**Pull request merged**
