### PR TITLE
Add Actinius Icarus board

### PR DESCRIPTION
**Pull request by iosifmacesanu**
Add Actinius Icarus board configuration to be able to access serial recovery mode

### CODE REVIEW

**Comment by sigvartmh** [comment]
@iosifmacesanu Just split the line which is over 72 in your commit message with `git commit --amend` and force push.

**Comment by iosifmacesanu** [comment]
@sigvartmh Thanks, I updated the pull request.

**Comment by sigvartmh** [comment]
True enough @iosifmacesanu make a PR with this change towards https://github.com/JuulLabs-OSS/mcuboot/ and it will be downstreamed into this repository

**Comment by iosifmacesanu** [comment]
Alright, thanks, will do that.

**Comment by alextsam** [comment]
@mbolivar can you comment whether there is going to be another merge from the upstream before the v1.1.0 release of nrfconnect? We have this PR merged already upstream and we are just very eager to have it available out of the box in v1.1.0
Thank you for any info you can provide!
Alex

**Comment by mbolivar** [comment]
> we are just very eager to have it available out of the box in v1.1.0

I hear you and we're discussing what can be done. Thanks!

**Comment by mbolivar** [comment]
> I hear you and we're discussing what can be done. Thanks!

@alextsam Please watch the cherry-pick from @sigvartmh: https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/pull/69

**Comment by alextsam** [comment]
> > I hear you and we're discussing what can be done. Thanks!
> 
> @alextsam Please watch the cherry-pick from @sigvartmh: #69

@mbolivar thank you for your help anyway!

**Pull request closed without merging**
