### PR TITLE
Multi image

### PR DESCRIPTION
**Pull request by tejlmand**
Update:
The PR now uses a series of reverts, and the reapplies the needed patches.

### CODE REVIEW

**Comment by mbolivar** [comment]
>     * It can be discussed if the changes introduced above should instead be applied as edits on the original commits, in order to reduce the size of the patch set to carry around.

In order to keep the 'west ncs-loot' output accurate and thus the next rebase clean, it would be better to see a revert + reapply style patch series. But if that is too complex, we can defer for now and clean up a bit during the rebase.

By the way, the revert+reapply rules are basically just a way to maintain a [quilt](https://en.wikipedia.org/wiki/Quilt_(software)) patch stack in git.

**Comment by tejlmand** [comment]
> 
> 
> > ```
> > * It can be discussed if the changes introduced above should instead be applied as edits on the original commits, in order to reduce the size of the patch set to carry around.
> > ```
> 
> In order to keep the 'west ncs-loot' output accurate and thus the next rebase clean, it would be better to see a revert + reapply style patch series. But if that is too complex, we can defer for now and clean up a bit during the rebase.
> 
> By the way, the revert+reapply rules are basically just a way to maintain a [quilt](https://en.wikipedia.org/wiki/Quilt_(software)) patch stack in git.

Will do that.
Not difficult at all, I was just wondering what strategy you preferred.
And now that I know, I will follow that principle ;-)

**Comment by tejlmand** [comment]
> By the way, the revert+reapply rules are basically just a way to maintain a quilt patch stack in git.

@mbolivar had to revert a series of patches to get down to the [nrf noup] https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/commit/0fa1f04f8b43bcce1fe84e314c194f2ff6d28219 without to much merge conflicts and keeping history nice.
Then I reapplied all needed patches again.

Let me know if this has been done in desired way.

**Comment by mbolivar** [comment]
> Let me know if this has been done in desired way.

I had to hack up zephyr/west.yml a bit to use ncs-loot with it since mcuboot is not in the upstream manifest yet, but with that done, here is the resulting list of OOT patches:

```
- 65b76e3cbea653b275d22a162a10faf178588cea [nrf noup] zephyr: Remove duplication from Kconfig and cmake
- 4bcdaaddbfa9022c96aa81288fe6df2e65e34503 [nrf noup] boot: bootutil: Add shared crypto functions for ECDSA
- 0fa1f04f8b43bcce1fe84e314c194f2ff6d28219 [nrf noup] cmake: multi-image + partition manager
- df29916e333de18880f69209194f8a5214cd1f22 [nrf toup] bootutil: silence spurious GCC warning
- 6b3540266ed26e09ad9563402a07c4958471be77 [nrf toup] fix documentation build
- 7fedf1d1887e58354e43240fb0813c501adc0882 [nrf fromlist] cmake: image-ify DTC_OVERLAY_FILE
- 0f73241f0f96db5bfe3150d1dd03c0aba296054b [nrf toup] cmake: make update.hex without trailer data
- cfe07dab6fc5cbf3d1aee5e7e3705c3f4ffbde79 [nrf toup] kconfig: use template for partition manager config
- 74d2f039cba394c4b368c078625b442835707db0 [nrf noup] boot/zephyr: pm adaptation after macro updates
- b67ab0f792e73f3ba96a47d0f1ac55630289bc8b [nrf toup] cmake: use function for signing application
- 73f46d1e21fc45be2dbe59ab487ab53971f037b4 [nrf toup] cmake: sign s0 and s1 with mcuboot's imgtool
- 46edf6b36fc36c5ed73d5b25aa49d6c8a34fddcc [nrf toup] partition_manager: add partition alignment
- e1e545899f3342c08aec1c4ea43cde686e9c3a60 [nrf noup] cmake: inject kconfig from mcuboot cmakelist
- 3892cda9d33ce00bf849c0bb8651fb0e4d5689ba [nrf noup] zephyr: add NCS application boilerplate
- a5cffec803ac18766dfd8c4613e7a164265a11d7 [nrf toup] zephyr: enable progressive erase for nRF9160
- d46e7d083f16f17ec354a9e8d246bd754a805bc8 [nrf toup] zephyr: add support for Thingy:91
- 3db81a20bc4617c435a89732ed3f3cbd122c3595 [nrf noup] loader: support B0 -> B1 (S0 - S1) configuration
- a631263274e7220e008138e7f26c2d35bbcb2203 [nrf noup] bootutil: nrf_cc310: Bugfix for CC310 and shared crypto API
```

(I stripped out ones with a `ci:` area).

Does that look like what you want to see?

**Pull request merged**
