### PR TITLE
[DNM] [nrf mergeup] merge upsteram up to commit f84cc4b

### PR DESCRIPTION
**Pull request by nvlsianpu**
* enable MULTITHREADING by default except on nRF
* add minimal footprint configuration for nrf52
* a bunch of refactorings after the multi-image support introduction for down-size flash footprint
* scripts: Show image version while verifying + bugfix
* image: use explitic padding on dependency version 
* Use Ninja instead of Makefiles for Zephyr (mcuboot/samples)

### CODE REVIEW

**Comment by nvlsianpu** [comment]
cc @MarekPieta @hakonfam

**Comment by hakonfam** [comment]
We need some modifications for the `FLASH_AREA_IMAGE_PRIMARY` define, as this is now a function, not an integer as it was before.

**Comment by hakonfam** [comment]
This will fix it, should we have it as a separate commit after the mergeup?

```
diff --git a/boot/zephyr/include/sysflash/sysflash.h b/boot/zephyr/include/sysflash/sysfla
sh.h
index 905e6a6..c3fa7b2 100644
--- a/boot/zephyr/include/sysflash/sysflash.h
+++ b/boot/zephyr/include/sysflash/sysflash.h
@@ -6,8 +6,8 @@
 #if USE_PARTITION_MANAGER
 #include <pm_config.h>
 
-#define FLASH_AREA_IMAGE_PRIMARY    PM_MCUBOOT_PRIMARY_ID
-#define FLASH_AREA_IMAGE_SECONDARY  PM_MCUBOOT_SECONDARY_ID
+#define FLASH_AREA_IMAGE_PRIMARY(x)    PM_MCUBOOT_PRIMARY_ID
+#define FLASH_AREA_IMAGE_SECONDARY(x)  PM_MCUBOOT_SECONDARY_ID
 #define FLASH_AREA_IMAGE_SCRATCH    PM_MCUBOOT_SCRATCH_ID
 
 #else
```

**Comment by nvlsianpu** [comment]
@hakonfam Thanks for the patch - I will add commit after mergeup commit

**Comment by nvlsianpu** [comment]
@hakonfam updated

**Comment by hakonfam** [comment]
Any way we can get this moving? We are depending on the multi image functionality to continue developing the multi stage bootloader :)

**Comment by mbolivar** [comment]
> [no toup] boot/zephy: pm adaptation after macro updates

Should this be

```
[nrf toup] boot/zephyr: pm adaptation after macro updates
```

?

Otherwise this looks good structurally

**Comment by nvlsianpu** [comment]
@mbolivar Actually [nrf noup].

**Comment by carlescufi** [comment]
@SebastianBoe @hakonfam can you please take a look?

**Comment by nvlsianpu** [comment]
I moved merge base ahead up to master/head. Wait for CI trigger.

**Comment by mbolivar** [comment]
> @mbolivar Actually [nrf noup].

Since the job has failed CI, `boot/zephyr` also (not `boot/zephy`)

**Pull request merged**
