### PR TITLE
[nrf mergeup] Upmerge 09 March 2020

### PR DESCRIPTION
**Pull request by emob-nordic**
Regular upmerge.
MCUboot upsterm revison is v1.5.0

### CODE REVIEW

**Comment by hakonfam** [comment]
This patch is needed 
```
diff --git a/boot/zephyr/prj.conf b/boot/zephyr/prj.conf
index bae72ca..836afc6 100644
--- a/boot/zephyr/prj.conf
+++ b/boot/zephyr/prj.conf
@@ -17,7 +17,6 @@ CONFIG_BOOT_BOOTSTRAP=n
 CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
 CONFIG_BOOT_SIGNATURE_TYPE_RSA_LEN=2048
 CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=n
-CONFIG_BOOT_SIGNATURE_TYPE_ED25519=n
 
```

**Comment by nvlsianpu** [comment]
^^
looks like this kconfig gone, It ought not disappear,

**Comment by hakonfam** [comment]
> ^^
> looks like this kconfig gone in the upmerge, It ought not disappear,

Ah, I did not check that.

**Comment by nvlsianpu** [comment]
e66d2deee11ce1479c556ffc6ce59516ee41249a
image

**Comment by emob-nordic** [comment]
> [e66d2de](https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/commit/e66d2deee11ce1479c556ffc6ce59516ee41249a)

Yea... mb. I've wrongly resolved conflicts.

**Comment by de-nordic** [comment]
Testing it with nrf52840_pca10056.

**Comment by de-nordic** [comment]
Ok, seems that DFU serial recovery works fine. Tested with and without progressive erase, with use of mcumgr. Any other suggested tests?

**Comment by emob-nordic** [comment]
Can we merge this? @nvlsianpu @hakonfam

**Pull request merged**
